version: "3.3"
services:
  productpage:
    image: grupo23/productpage
    ports:
      - 9080:9080
    container_name: grupo23-productpage
    volumes:
      - productpage:/bookinfo/src/productpage

  details:
    image: grupo23/details
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
    container_name: grupo23-details
    depends_on:
      - productpage
    volumes:
      - details:/opt/microservices
    ports:
      - 9080
  reviews:
    image: grupo23/reviews
    container_name: grupo23-reviews
    environment:
      - SERVERDIRNAME=reviews
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=true
      - STAR_COLOR=black
    depends_on:
      - productpage
    ports:
      - 9080
    volumes:
      - reviews:/opt/ibm/wlp/usr/servers/defaultServer

  ratings:
    image: grupo23/ratings
    container_name: grupo23-ratings
    ports:
      - 9080
    environment:
      - SERVICE_VERSION=v1
    depends_on:
      - reviews
    volumes:
      - ratings:/opt/microservices

volumes:
  productpage:
  details:
  reviews:
  ratings:
