version: "3.3"
services:
  productpage:
    build:
      context: .
      dockerfile: Dockerfile-Productpage
    image: grupo23/productpage
    ports:
      - 9080:9080
    container_name: grupo23-productpage

  details:
    build:
      context: .
      dockerfile: Dockerfile-Details
    image: grupo23/details
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
    container_name: grupo23-details
    depends_on:
      - productpage
    ports:
      - 9080
      
  reviews:
    build:
      context: .
      dockerfile: Dockerfile-Reviews
    image: grupo23/reviews
    container_name: grupo23-reviews
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=true
      - STAR_COLOR=black
    depends_on:
      - productpage
    ports:
      - 9080

  ratings:
    build:
      context: .
      dockerfile: Dockerfile-Ratings
    image: grupo23/ratings
    container_name: grupo23-ratings
    ports:
      - 9080
    environment:
      - SERVICE_VERSION=v1
    depends_on:
      - reviews

