FROM node:12.18.1-slim
  
COPY practica_creativa2/bookinfo/src/ratings/package.json /opt/microservices/
COPY practica_creativa2/bookinfo/src/ratings/ratings.js /opt/microservices/

ENV SERVICE_VERSION=v1

WORKDIR /opt/microservices

RUN npm install

EXPOSE 9090

CMD ["node", "ratings.js", "9080"]
