FROM node:12.18.1-slim
  
COPY p2/bookinfo/src/ratings/package.json opt/microservices/
COPY p2/bookinfo/src/ratings/ratings.js opt/microservices/

ENV SERVICE_VERSION=v1

WORKDIR /opt/microservices

RUN npm install

EXPOSE 9090

CMD ["node", "ratings.js", "9080"]
